### PR TITLE
animations added

### PR DESCRIPTION
**Pull request by shivangigoel1302**

### CODE REVIEW

**Comment by prabaljainn** [comment]
there are some conflicts in index.html

**Comment by prabaljainn** [comment]
@shivangigoel1302 Try something more

**Comment by shivangigoel1302** [comment]
Hey what conflicts are there? I am not able to notice on the console too. can you please let me know so that I can look into it? Also can you please mention hactoberfest tag in your repo as the PR didn't get counted.

**Comment by shivangigoel1302** [comment]
I will definitely try more. Also can you add the hactober accepted label please for the pr to get counted

**Pull request merged**
